export const CATEGORIES = [
  "Personal Development",
  "Mental Health",
  "Travel & Culture",
  "Life Lessons",
  "Community Building",
  "Authentic Living",
  "Self-Awareness & Identity",
  "Emotional Well-Being",
  "Purpose & Meaning",
  "Creativity & Expression",
  "Relationships & Human Connections",
  "Mindfulness & Inner Peace",
  "Growth & Transformation",
  "Work Dreams & Ambition",
  "Society & Human Behaviour",
  "Healing & Acceptance",
  "Philosophy & Spirituality",
  "Everyday Life & Observations",
  "Change & Transitions",
  "Resilience & Overcoming",
  "Inspiration & Motivation",
];
